# RoundRobin, P2C
strategy = "RoundRobin"

# per-route timeout, supports wildcard * in path, in milliseconds
[route_timeout]
"/hello" = 3000
"/*/heelo" = 301

[cluster]
# someserviceendpoint = ["localhost:8314", "localhost:8315", "localhost:8316", "localhost:8317"]
# someserviceendpoint = ["localhost:8317"]
someserviceendpoint = ["localhost:8314"]
