[package]
name = "control-plane"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.6"
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = ["full"] }
side-car-proxy = { path = "../side-car-proxy" }
